-- =======================================================
-- MEMOSTACK DATABASE SCHEMA (Oracle 12c+ / 21c compatible)
-- =======================================================

-- [필수] SYSTEM 계정 접속 시 XEPDB1(플러거블 데이터베이스) 영역으로 컨테이너를 전환합니다.
ALTER SESSION SET CONTAINER = XEPDB1;

-- 1. 유저 테이블 (관리자 로그인용)
CREATE TABLE memo_stack_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 2. 게시글 테이블
CREATE TABLE posts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 3. 태그 테이블
CREATE TABLE tags (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE
);

-- 4. 게시글-태그 매핑 관계 테이블
CREATE TABLE post_tags (
    post_id NUMBER NOT NULL,
    tag_id NUMBER NOT NULL,
    PRIMARY KEY (post_id, tag_id),
    CONSTRAINT fk_posts FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    CONSTRAINT fk_tags FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE
);

-- 5. 인덱스 설정 (검색 성능 최적화)
CREATE INDEX idx_posts_title ON posts(title);
CREATE INDEX idx_tags_name ON tags(name);
CREATE INDEX idx_post_tags_post ON post_tags(post_id);
CREATE INDEX idx_post_tags_tag ON post_tags(tag_id);
